############################################################
# +------------------------------------------------------+ #
# |               Timecounter  插件设置                  | #
# +------------------------------------------------------+ #
############################################################
Setting:
  autoSaveTime: 120 #自动保存间隔时长
Database:
  status: false #是否开启数据库模式
  host: localhost #数据库地址
  port: 3306 #数据库端口
  user: root #数据库账号
  password: root #数据库密码
  database: timecount #数据库库名
  charset: utf-8 #字符集编码